baseURL = 'https://log.batako.net/'
languageCode = 'ja'
title = 'バタコのチラ裏'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
theme = 'ananke'

[languages]
  [languages.ja]
    languageName = '日本語'
    weight = 1
